from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('admindashboard/', views.admindashboard, name='admindashboard'),
    path('userdashboard/', views.userdashboard, name='userdashboard'),
    path('adminsidebar/', views.admin_sidebar, name='admin_sidebar'),
    path('adminnavbar/', views.admin_navbar, name='admin_navbar'),
    path("addproduct/", views.addproduct, name="addproduct"),
    path("addcategory/", views.addcategory, name="addcategory"),
    path("incomeorder/", views.incomeorder, name="incomeorder"),
    path("users/", views.users, name="users"),
    path("addrestaurant/", views.addrestaurant, name="addrestaurant"),
    path("banner/", views.banner, name="banner"),
    path("coupon/", views.coupon, name="coupon"),
    path("settings/", views.settings, name="settings"),
    path("edit-admin-profile/",views.edit_admin_profile,name="edit_admin_profile"),
    path("add-product-form/", views.add_product_form, name="add_product_form"),
    path("addcategoryform/", views.addcategoryform, name="addcategoryform"),
    path("deletecategory/<int:id>/",views.deletecategory,name="deletecategory"),
    path("editcategory/<int:id>/",views.editcategory,name="editcategory"),
    path('sidebar/', views.sidebar, name='sidebar'),
    path('navbar/', views.navbar, name='navbar'),
    path('banner/',views.banner,name='banner'),
    path('addnewbanner/',views.addnewbanner,name='addnewbanner'),
    path('editbanner/<int:id>/', views.editbanner, name='editbanner'),
    path('deletebanner/<int:id>/', views.deletebanner, name='deletebanner'),
    path("category/", views.category, name="category"),
    path('cart/', views.cart, name='cart'),
    path('addtocart/<int:id>/', views.addtocart, name='addtocart'),
    path('buynow/<int:id>/', views.buynow, name='buynow'),
    path('removecart/<int:id>/', views.removecart, name='removecart'),
    path('payment/', views.payment, name='payment'),
    path('ordersuccess/', views.ordersuccess, name='ordersuccess'),
    path('acceptorder/<int:id>/', views.acceptorder, name='acceptorder'),
    path('updateorderstatus/<int:id>/', views.updateorderstatus, name='updateorderstatus'),
    path('myorders/', views.myorders, name='myorders'),
]