# Generated by Django 5.2.10 on 2026-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='category')),
                ('displayorder', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
